"""
Reads data/calls_ledger.csv and writes data/ledger.json.

Usage: py scripts/export_json.py
"""
import csv
import json
from pathlib import Path

ROOT = Path(__file__).parent.parent
SRC  = ROOT / "data" / "calls_ledger.csv"
DEST = ROOT / "data" / "ledger.json"

CONVICTION_WEIGHT = {"**": 2, "*": 1, "-": 0, "": None}

def parse_bool(v):
    return v.strip().upper() == "TRUE"

def parse_tags(v):
    return [t.strip() for t in v.split("|") if t.strip()] if v.strip() else []

def parse_related(v):
    return [t.strip() for t in v.split("|") if t.strip()] if v.strip() else []

def conviction_weight(conviction_str):
    c = conviction_str.strip()
    if c in ("★★", "**"):   return 2
    if c in ("★", "*"):           return 1
    if c in ("—", "–", "-"): return 0
    return None   # pre-2025 equal-weight calls

def extract_year(call_id):
    try:
        return int(call_id.split("-")[0])
    except:
        return None

def main():
    calls = []
    with open(SRC, newline="", encoding="utf-8") as f:
        for row in csv.DictReader(f):
            year = extract_year(row["call_id"])
            c_str = row.get("conviction", "").strip()
            weight = conviction_weight(c_str)
            calls.append({
                "call_id":           row["call_id"],
                "date_made":         row["date_made"],
                "call_text":         row["call_text"],
                "domain":            row["domain"],
                "tags":              parse_tags(row["tags"]),
                "conviction":        c_str if c_str else None,
                "weight":            weight,
                "time_horizon":      row["time_horizon"],
                "status":            row["status"],
                "resolution_date":   row["resolution_date"] or None,
                "resolution_note":   row["resolution_note"] or None,
                "source_url":        row["source_url"] or None,
                "source_title":      row["source_title"] or None,
                "related_calls":     parse_related(row["related_calls"]),
                "pre_consensus":     parse_bool(row["pre_consensus_score"]),
                "confidence_band":   row.get("confidence_band") or None,
                "year":              year,
            })

    output = {
        "_note": (
            "RDI Call Ledger — machine-readable. "
            "Master source: data/calls_ledger.csv. "
            "Generated by scripts/export_json.py. "
            "Do not edit this file directly."
        ),
        "generated": __import__("datetime").date.today().isoformat(),
        "total": len(calls),
        "calls": calls,
    }

    DEST.write_text(json.dumps(output, ensure_ascii=False, indent=2), encoding="utf-8")
    print(f"Exported {len(calls)} calls -> {DEST}")

    # Quick sanity summary
    from collections import Counter
    statuses = Counter(c["status"] for c in calls)
    domains  = Counter(c["domain"] for c in calls)
    print("\nStatus breakdown:")
    for s, n in statuses.most_common():
        print(f"  {s}: {n}")
    print("\nDomain breakdown:")
    for d, n in domains.most_common():
        print(f"  {d}: {n}")

if __name__ == "__main__":
    main()
